site_name: LMS Manual
theme: 
  name: material
  locale: kr
  features:
    - navigation.top
  palette:
    primary: indigo
nav:
  - 소개:
    - OpenOLAT에 대한 정보: info/info1.md
    - OpenOLAT 작업 시 요구사항: info/info2.md
    - 오픈 소스 소프트웨어의 아이디어: info/info3.md
    - 기술 및 탐색: info/info4.md
    - 역할 및 권한: info/info5.md
    - 코치: info/info6.md
    - 게스트 액세스: info/info7.md

  - 로그인, 가입 및 로그아웃:
    - 로그인 페이지: login/login1.md
    - 세션 시간 초과 및 로그아웃: login/login2.md

  - 개인 메뉴 및 일반 구성 요소: 
    - 개인 메뉴: 
      - 개요: personal/personal1-1.md
      - 달력: personal/personal1-2.md
      - 개인 폴더: personal/personal1-3.md
      - 이메일: personal/personal1-4.md
    - 구성: 
      - 개요: personal/personal2-1.md
      - 코로나 증명서: personal/personal2-2.md
    - 전체 텍스트 검색: personal/personal3.md
    - 채팅: personal/personal4.md
    - 포털 구성: personal/personal5.md
    - 수학 공식: personal/personal6.md
    - 테이블 작업: personal/personal7.md

  - 그룹:
    - 그룹 생성: group/group1.md
    - 그룹 관리: group/group2.md
    - LTI 액세스: group/group3.md
    - 그룹 도구 사용: group/group4.md
    - 그룹 관리: group/group5.md

  - 코스 및 카탈로그: 
    - 코스 찾기: course_and_catalog/course_and_catalog1.md
    - 정보 페이지: course_and_catalog/course_and_catalog2.md

  - 코스 학습활동:
    - 코스 요소 작업:
      - 개요: learning_activities_in_course/learning_activities_in_course1-1.md
      - 포럼 작업: learning_activities_in_course/learning_activities_in_course1-2.md
      - 작업 및 그룹 작업 사용: learning_activities_in_course/learning_activities_in_course1-3.md
      - 테스트 작업: learning_activities_in_course/learning_activities_in_course1-4.md
      - 주제 할당 작업: learning_activities_in_course/learning_activities_in_course1-5.md
      - 위키로 작업하기: learning_activities_in_course/learning_activities_in_course1-6.md
    - 추가 코스 기능: learning_activities_in_course/learning_activities_in_course2.md
    - 시험: learning_activities_in_course/learning_activities_in_course3.md
    - 코스 문제 및 오류 메시지: learning_activities_in_course/learning_activities_in_course4.md

  - 저작:
    - 다양한 유형의 학습 리소스: authoring/authoring1.md
    - 작성 섹션의 작업: authoring/authoring2.md
    - 학습 리소스의 상세 보기: authoring/authoring3.md
    - 정보 페이지 설정: authoring/authoring4.md
    - 리소스 및 사용에 대한 기술 정보: authoring/authoring5.md

  - 코스 만들기:
    - 일반 정보: course_create/course_create1.md
    - 코스 편집기를 사용한 코스의 5단계: course_create/course_create2.md
    - 코스 마법사: course_create/course_create3.md
    - 코스:
      - 개요: course_create/course_create4-1.md
      - 학습 경로 과정 만들기: course_create/course_create4-2.md
      - 코스: course_create/course_create4-3.md
      - 코스들: course_create/course_create4-4.md
    - 코스 요소의 일반 구성:
      - 개요: course_create/course_create5-1.md
      - 코스 요소 삭제, 이동 및 복사: course_create/course_create5-2.md
      - 전문가 모드에서 액세스 제한: course_create/course_create5-3.md
    - 추가 코스 편집기 도구 사용: course_create/course_create6.md
    - 코스 설정:
      - 개요: course_create/course_create7-1.md
      - LTI 액세스: course_create/course_create7-2.md
      - 코스 및 코스 요소의 디자인 가능성: course_create/course_create7-3.md
    - 액세스 구성: course_create/course_create8.md

  - 과정 요소의 유형:
    - 지식 이전: 
      - 개요: course_element/course_element1-1.md
      - 코스 요소 구조: course_element/course_element1-2.md
      - 코스 요소 폴더: course_element/course_element1-3.md
      - 코스 요소 단일 페이지: course_element/course_element1-4.md
      - 코스 요소 SCORN 학습 컨텐츠: course_element/course_element1-5.md
      - 코스 요소 card2brain Flashcards: course_element/course_element1-6.md
      - 코스 요소 미디어 사이트: course_element/course_element1-7.md
    - 평가: 
      - 개요: course_element/course_element2-1.md
      - 코스 요소 평가: course_element/course_element2-2.md
      - 코스 요소 체크리스트: course_element/course_element2-3.md
    - 커뮤니케이션 및 협업: 
      - 개요: course_element/course_element3-1.md
      - 가상 교실: course_element/course_element3-2.md
      - 코스 요소 Adobe Connect: course_element/course_element3-3.md
      - 코스 요소 BigBlueButton: course_element/course_element3-4.md
      - BBB - 자주 묻는 질문: course_element/course_element3-5.md
      - 코스 요소 GoToMeeting: course_element/course_element3-6.md
      - 코스 요소 OpenMeetings: course_element/course_element3-7.md
      - 코스 요소 비테로: course_element/course_element3-8.md
      - 코스 요소 Microsoft Teams: course_element/course_element3-9.md
    - 관리 및 조직: course_element/course_element4.md
    - 다른: course_element/course_element5.md

  - 코스 운영:
    - 코스 도구 사용:
      - 개요: course_operation/course_operation1-1.md
      - 회원 관리: course_operation/course_operation1-2.md
      - 저장 폴더: course_operation/course_operation1-3.md
      - 평가도구: 
        - 개요: course_operation/course_operation1-4-1.md
        - 탭 사용자: course_operation/course_operation1-4-2.md
        - 학습자 평가: course_operation/course_operation1-4-3.md
        - 코스 모듈 평가: course_operation/course_operation1-4-4.md
        - 작업 및 그룹 작업 평가: course_operation/course_operation1-4-5.md
        - 테스트 평가: course_operation/course_operation1-4-6.md
        - 평가 양식: course_operation/course_operation1-4-7.md
        - 등급/평가 척도: course_operation/course_operation1-4-8.md
      - 강의 및 결석: 
        - 개요: course_operation/course_operation1-5-1.md
        - 강의 학생보기: course_operation/course_operation1-5-2.md
        - 강의 교사보기: course_operation/course_operation1-5-3.md
      - 코스 알림: course_operation/course_operation1-6.md
      - 데이터 보관: course_operation/course_operation1-7.md
      - 코스 활동 기록: course_operation/course_operation1-8.md
    - 추가 코스 기능 사용하기: course_operation/course_operation2.md

  - 어떻게..: 
    - ... 제출 작업에 대한 일괄 평가 생성: how/how1.md
    - ... CSS를 사용하여 코스 디자인 사용자 지정: how/how2.md
    - ... 여러 코스에서 동일한 파일 사용: how/how3.md

  - 전자 평가:
    - 평가 모드: e_assessment/e_assessment1.md
    - 성능 평가: e_assessment/e_assessment2.md
    - 코칭: e_assessment/e_assessment3ee.md

  - CP 학습 컨텐츠 제작:
    - 컨텐츠 패키지를 위한 5단계: resource_cp/resource_cp1.md
    - CP 에디터: resource_cp/resource_cp2.md

  - 위키 만들기:
    - 위키를 만드는 4단계: resource_wiki/resource_wiki1.md

  - 동영상 만들기:
    - 학습 자료 비디오: resource_video/resource_video1.md
    - 코스 요소 비디오: resource_video/resource_video2.md
    - 단일 페이지 동영상 추가 편집: resource_video/resource_video3.md
    - 동영상 업로드: resource_video/resource_video4.md

  - 팟캐스트 만들기:
    - 팟캐스트를 위한 4단계: resource_podcast/resource_podcast1.md
    - 팟 캐스트: resource_podcast/resource_podcast2.md

  - 블로그 만들기:
    - 블로그를 위한 4단계: resource_blog/resource_blog1.md
    - 블로그: resource_blog/resource_blog2.md

  - 작업 생성:
    - 작업을 위한 3단계: task/task1.md
    - 작업 추가구성: task/task2.md
    - 작업 평가: task/task3.md

  - 포트폴리오 만들기:
    - 포트폴리오 일반 정보: portfolio/portfolio1.md
    - 포트폴리오 구성 요소:
      - 개요: portfolio/portfolio2-1.md
      - 내 포트폴리오 바인더: portfolio/portfolio2-2.md
      - 내 항목: portfolio/portfolio2-3.md
      - 미디어 센터: portfolio/portfolio2-4.md
      - 내가 공유함: portfolio/portfolio2-5.md
      - 나와 공유됨: portfolio/portfolio2-6.md
    - 포트폴리오 바인더의 3단계: portfolio/portfolio3.md
    - 포트폴리오 편집기: portfolio/portfolio4.md
    - 항목의 다중 사용: portfolio/portfolio5.md
    - 역량 태그: portfolio/portfolio6.md
    - 평가 포트폴리오 프로세스: 
      - 개요: portfolio/portfolio7-1.md
      - 포트폴리오 템플릿 생성: portfolio/portfolio7-2.md
      - 포트폴리오 템플릿 관리 및 편집: portfolio/portfolio7-3.md
      - 포트폴리오 작업 생성: portfolio/portfolio7-4.md
      - 포트폴리오 작업 및 할당 수집 및 편집: portfolio/portfolio7-5.md
      - 포트폴리오 할당 채점: portfolio/portfolio7-6.md

  - 주제 할당 주제 관리:
    - 주제 생성 및 관리를 위한 3단계: topic_assignment/topic_assignment1.md

  - 양식 만들기:
    - Forms에 대한 일반 정보: forms/forms1.md
    - 양식을 위한 3단계: forms/forms2.md
    - 양식 편집기(설문지 편집기):
      - 개요: forms/forms3-1.md
      - 표제: forms/forms3-2.md
      - 질문 규칙: forms/forms3-3.md
    - 코스의 양식:
      - 개요: forms/forms4-1.md
      - Forms 요소의 양식: forms/forms4-2.md
      - 설문지의 양식: forms/forms4-3.md
      - 루브릭 채점 양식: forms/forms4-4.md
      - ePortfolio 템플릿의 양식: forms/forms4-5.md

  - 테스트 생성:
    - 테스트에 대한 일반 정보: tests/tests1.md
    - 테스트 또는 자체 테스트를 위한 4단계: tests/tests2.md
    - 테스트 편집기 QTI 2.1:
      - 개요: tests/tests3-1.md
      - 테스트 질문 유형: tests/tests3-2.md
      - 테스트 질문 구성: tests/tests3-3.md
      - 테스트 구성: tests/tests3-4.md
    - 테스트 설정: tests/tests4.md
    - 코스 수준의 테스트: tests/tests5.md
    - QTI 1.2에서 QTI 2.1로 변경: tests/tests6.md

  - 질문 은행:
    - 데이터 관리: question_bank/question_bank1.md
    - 항목 상세보기: question_bank/question_bank2.md
    - 문제 은행 가능한 작업: question_bank/question_bank3.md
    - 검색: question_bank/question_bank4.md
    - 문제 풀 공유 옵션: question_bank/question_bank5.md
    - 문제 은행 검토 프로세스: question_bank/question_bank6.md
    - 질문 은행 관리: question_bank/question_bank7.md

  - 커리큘럼 관리: curriculum_management/curriculum_management1.md

  - 지원되는 기술:
    - WebDAV 사용: supported_tech/supported_tech1.md